run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - gosec
    - bodyclose
    - noctx
    - exhaustive
    - prealloc

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/stainedhead/gojira-tmux
  govet:
    enable-all: true
    disable:
      - shadow
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
    - path: mock_
      linters:
        - unused
